language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install nasm qemu
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50

install:
  - make

script: echo "Build Finished."
